# Generated by Django 3.2.4 on 2021-06-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='title',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
    ]
